### PR TITLE
Support for insert() and last modification time

### PR DESCRIPTION
**Pull request by mikrosk**
Maybe you would be interested to include this functionality? I use it to my great satisfaction but I'm lazy to setup a maven repository so I'm stuck with hard copied files into my project.

### CODE REVIEW

**Comment by commonsguy** [comment]
I have no particular interest in having `StreamProvider` be read-write. Similarly, I have no interest in supporting arbitrary filesystem paths via `root-path`. I appreciate that you had those itches to scratch, but they are not my itches, and I am not very interested in taking on the long-term maintenance of things with those sorts of security characteristics.

What I *should* do is ensure that changes like what you want could be handled easily via subclassing, rather than having to directly modify the project. So, for example, your `canInsert()` concept makes sense, and I ought to do that or something along those lines. I have filed issue #11 to track that work.

I apologize for not taking on all your code, but I will try to make it easier for you to maintain what you have over the long term.

**Comment by mikrosk** [comment]
No worries, if you find time to implement some kind of extensible interface, that would be great.

**Comment by commonsguy** [comment]
FYI, some [recent moves by Google](https://commonsware.com/blog/2016/03/14/psa-file-scheme-ban-n-developer-preview.html) has driven me to work on revamping `StreamProvider`, to also provide parallel support for `DocumentProvider` and the Storage Access Framework.

On the plus side, this will include read/write support (at least, for data sources where that's practical, like files) and a clear plan for adding support for new "routes" (`Uri` mapping to a particular `StreamStrategy`, optionally driven by the XML metadata) in subclasses. This work should handle your use cases.

On the minus side, this will be a substantial rewrite. Largely, that's because the Storage Access Framework requires you to extend `DocumentProvider` instead of `ContentProvider`, so I will be extracting the guts of `StreamProvider` into a separate class, with `StreamProvider` and `StreamDocumentProvider` as wrappers. Plus, `CompositeStreamStrategy` isn't going to scale well, so I am going to implement `Route` and `Route.Builder` and stuff to provide more flexibility, particularly for subclasses. However, I'm going to be seriously breaking your existing subclass, though the results should be worth it.

**Comment by mikrosk** [comment]
That sounds interesting. I'm not worried about breaking the current implementation, if the future version will provide the same functionality, it's totally OK for me, even if I'd need to tweak some bits again. Looking forward to your updates!

**Comment by commonsguy** [comment]
FYI, I just shipped v0.4.0. Everything from your pull request was either integrated or should be able to be implemented via subclassing, without modifying `StreamProvider` or related classes directly. If you try this and find that I missed some extension points that you need, file issues for them, and I'll look to add them.

**Pull request closed without merging**
